name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # Menjalankan setiap 2 jam (opsional, bisa diubah)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: iqram21  # Ganti dengan username GitHub Anda
          svg_out_path: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg
